CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	slug TEXT UNIQUE NOT NULL,
	title TEXT NOT NULL,
	summary TEXT NOT NULL,
	content TEXT NOT NULL,
	tags TEXT NOT NULL,
	published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	reading_time TEXT NOT NULL DEFAULT '3 min read'
);
